### ISSUE TITLE
Search fails with more than 3 words

### ISSUE THREAD

**Issue by Oldiesmann** [WildPHP/module-aggregator#1]
Trying to search Wikipedia, AUR, etc. with more than three words fails with an "Invalid parameters" error.

```
<Oldiesmann> !w Red Fish Blue Fish
<Botergos> Invalid arguments. Please check !cmdhelp w for usage instructions.
```

**Comment by NanoSector** [comment]
Affected line: https://github.com/WildPHP/module-aggregator/blob/master/src/Aggregator.php#L83

Command should accept unlimited parameters. Will be fixed when implementing the new commands structure.

**Comment by NanoSector** [comment]
Fixed with new commands structure. Code will be up later, no plans for release yet.
